# frozen_string_literal: true

require_relative "cyborg/version"
require_relative "cyborg/clock"
require_relative "cyborg/errors"
require_relative "cyborg/bridge/canonical_json"
require_relative "cyborg/bridge/envelope"
require_relative "cyborg/bridge/artifact_store"
require_relative "cyborg/redactor"
require_relative "cyborg/config"
require_relative "cyborg/paths"
require_relative "cyborg/calendar"
require_relative "cyborg/database"
require_relative "cyborg/domain"
require_relative "cyborg/repositories/run_repository"
require_relative "cyborg/repositories/source_repository"
require_relative "cyborg/repositories/record_repository"
require_relative "cyborg/repositories/action_repository"
require_relative "cyborg/repositories/analysis_repository"
require_relative "cyborg/repositories/cache_repository"
require_relative "cyborg/repositories/presentation_repository"
require_relative "cyborg/runs/lease_manager"
require_relative "cyborg/runs/lifecycle"
require_relative "cyborg/sources/contracts"
require_relative "cyborg/sources/repository_discovery"
require_relative "cyborg/sources/git_attribution"
require_relative "cyborg/sources/local_git_adapter"
require_relative "cyborg/cli"
